[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gsi"
version = "0.0.1"
description = "Geodetic Scene Illustrator: A Python package for creating geodetic illustrations"
authors = [
    {name = "bbyel"}
]
dependencies = [
    "numpy",
    "matplotlib",
    "shapely",
]
